CREATE TABLE "historical_club_team_stats" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"game_title_id" integer NOT NULL,
	"playlist" text NOT NULL,
	"games_played" integer,
	"wins" integer,
	"losses" integer,
	"otl" integer,
	"win_loss_streak" integer,
	"did_not_finish_pct" numeric(5, 2),
	"dnf_wins" integer,
	"division_titles" integer,
	"club_finals_gp" integer,
	"goals_for" integer,
	"goals_against" integer,
	"goal_difference" integer,
	"avg_goals_for" numeric(5, 2),
	"avg_goals_against" numeric(5, 2),
	"avg_win_margin" numeric(5, 2),
	"avg_loss_margin" numeric(5, 2),
	"shots_for" integer,
	"shots_against" integer,
	"shots_per_game" numeric(5, 2),
	"avg_shots_against" numeric(5, 2),
	"shooting_pct" numeric(5, 2),
	"hits" integer,
	"hits_per_game" numeric(5, 2),
	"pim" integer,
	"avg_pim" numeric(5, 2),
	"power_plays" integer,
	"power_play_goals" integer,
	"power_play_pct" numeric(5, 2),
	"power_play_kill_pct" numeric(5, 2),
	"times_shorthanded" integer,
	"short_handed_goals" integer,
	"short_handed_goals_against" integer,
	"faceoffs_won" integer,
	"faceoff_pct" numeric(5, 2),
	"breakaways" integer,
	"breakaway_pct" numeric(5, 2),
	"one_timer_goals" integer,
	"one_timer_pct" numeric(5, 2),
	"passes" integer,
	"pass_attempts" integer,
	"passing_pct" numeric(5, 2),
	"blocked_shots" integer,
	"avg_time_on_attack" text,
	"source_asset_paths" text[] NOT NULL,
	"raw_extract_json" jsonb NOT NULL,
	"import_batch" text NOT NULL,
	"review_status" text DEFAULT 'pending_review' NOT NULL,
	"confidence_score" numeric(5, 2),
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "historical_club_team_stats" ADD CONSTRAINT "historical_club_team_stats_game_title_id_game_titles_id_fk" FOREIGN KEY ("game_title_id") REFERENCES "public"."game_titles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "hct_stats_title_playlist_uniq" ON "historical_club_team_stats" USING btree ("game_title_id","playlist");