// GENERATED by docs/design/handoffs/2026-10-cards/port-badge-skins.mjs — do not edit by hand.
// Default badge skin per card theme (badge-levels.js SKINS/skinFor) and the
// base tier the Player Badges design merges them onto (card-data.js BADGE_TIERS[3]).
import type { CardThemeKey } from '@eanhl/db/cards'

export interface BadgeSkin {
  outer: string
  fill: string
  icon: string
  label: string
  inset: number
  filter: string
  gap?: string
  inner?: string
  gloss?: boolean
}

export const BADGE_BASE_SKIN: BadgeSkin = {
  outer: 'linear-gradient(160deg, #f4f4f5, #71717a 50%, #d4d4d8)',
  fill: '#121011',
  icon: '#f4f4f5',
  label: '#d4d4d8',
  inset: 2,
  filter: 'none',
}

export const BADGE_SKINS: Readonly<Record<CardThemeKey, BadgeSkin>> = {
  away: {
    outer: 'linear-gradient(160deg, #d4d4d8, #71717a 50%, #a1a1aa)',
    inner: '#c9c9cc',
    fill: 'linear-gradient(180deg, #f4f4f5, #dcdcde)',
    icon: '#52525b',
    label: '#52525b',
    inset: 2,
    gap: '#e9e9eb',
    filter: 'none',
  },
  home: {
    outer: '#52525b',
    fill: 'linear-gradient(180deg, #1f1d1e, #131112)',
    icon: '#d4d4d8',
    label: '#a1a1aa',
    inset: 1.8,
    gap: '#0c0b0c',
    filter: 'none',
  },
  alternate: {
    outer: 'linear-gradient(160deg, #ffd9d4, #e84131 35%, #7a1a10 65%, #ef6a5e)',
    inner: '#7a1a10',
    fill: 'linear-gradient(180deg, #1a1213, #0c0707)',
    icon: '#ffffff',
    label: '#ef6a5e',
    inset: 2,
    gap: '#0c0707',
    filter: 'none',
  },
  carbon: {
    outer:
      'linear-gradient(135deg, #f4f4f5 0%, #71717a 14%, #27272a 28%, #e84131 40%, #7a1a10 46%, #a1a1aa 58%, #3f3f46 72%, #e4e4e7 86%, #52525b 100%)',
    fill: 'linear-gradient(118deg, rgba(255,255,255,0.10) 0%, transparent 30%, transparent 56%, rgba(255,255,255,0.06) 68%, transparent 80%), linear-gradient(27deg, #0c0c0c 2.5px, transparent 2.5px) 0 2.5px/10px 10px, linear-gradient(207deg, #0c0c0c 2.5px, transparent 2.5px) 5px 0/10px 10px, linear-gradient(27deg, #2c2c2e 2.5px, transparent 2.5px) 0 5px/10px 10px, linear-gradient(207deg, #2c2c2e 2.5px, transparent 2.5px) 5px 2.5px/10px 10px, linear-gradient(90deg, #1c1c1d 5px, transparent 5px) 0 0/10px 10px, linear-gradient(#262628 25%, #151516 25%, #151516 50%, transparent 50%, transparent 75%, #303033 75%, #303033) 0 0/10px 10px, linear-gradient(#0e0e0e, #0e0e0e)',
    icon: '#ffffff',
    label: '#e4e4e7',
    inset: 2,
    gap: '#0c0c0c',
    filter: 'none',
  },
  futureB: {
    outer:
      'linear-gradient(160deg, #ef6a5e 0%, #3a1410 22%, #0b0c14 50%, #3a1410 78%, #e84131 100%)',
    fill: 'radial-gradient(70% 26% at 50% 54%, rgba(232,65,49,0.55), transparent 70%), linear-gradient(180deg, #07080e 0 54%, transparent 54%), linear-gradient(180deg, transparent 54%, rgba(239,106,94,0.85) 54% 55.5%, transparent 55.5% 61%, rgba(232,65,49,0.55) 61% 62%, transparent 62% 71%, rgba(232,65,49,0.45) 71% 72%, transparent 72% 85%, rgba(232,65,49,0.4) 85% 86.5%, transparent 86.5%), linear-gradient(180deg, transparent 54%, rgba(0,0,0,0) 54%), repeating-conic-gradient(from 90deg at 50% 54%, rgba(232,65,49,0.5) 0deg 1.4deg, transparent 1.4deg 16deg), linear-gradient(180deg, #07080e 0%, #05060a 60%, #030305 100%)',
    icon: '#ffffff',
    label: '#ffc2bb',
    inset: 2,
    gap: '#05060a',
    filter: 'drop-shadow(0 0 8px rgba(232,65,49,0.45))',
  },
  frozen: {
    outer:
      'linear-gradient(150deg, #ffffff 0%, #bfe3f2 18%, #4f7d96 38%, #eaf7fc 54%, #3a6075 74%, #d4eef8 100%)',
    fill: "radial-gradient(70% 40% at 20% 0%, rgba(225,243,251,0.30), transparent 70%), linear-gradient(180deg, rgba(10,32,46,0.20) 0%, rgba(8,26,38,0.45) 40%, rgba(5,16,24,0.75) 70%, rgba(3,9,14,0.92) 100%), url('/images/badges/tex-ice-glacier.webp') center/cover no-repeat, #060c11",
    icon: '#eaf7fc',
    label: '#d4eef8',
    inset: 2.2,
    gap: '#071620',
    filter: 'drop-shadow(0 0 8px rgba(190,228,245,0.35))',
  },
  futureC: {
    outer:
      'linear-gradient(160deg, #f1e8ff 0%, #8a5cff 22%, #2a1655 46%, #d9c6ff 62%, #ff4fd8 80%, #5b34c9 100%)',
    fill: "linear-gradient(180deg, rgba(5,3,11,0) 0%, rgba(5,3,11,0.2) 40%, rgba(5,3,11,0.6) 70%, rgba(5,3,11,0.8) 100%), url('/images/badges/tex-future-circuit.webp') center/cover no-repeat, #0a0616",
    icon: '#f1e8ff',
    label: '#e9dcff',
    inset: 2,
    gap: '#0a0616',
    filter: 'drop-shadow(0 0 9px rgba(160,110,255,0.45))',
  },
  inferno: {
    outer:
      'linear-gradient(160deg, #c9a07a 0%, #a8361a 14%, #2a0c06 34%, #140806 50%, #6e1c0c 70%, #b0451c 88%, #c9a07a 100%)',
    fill: "radial-gradient(80% 45% at 50% 100%, rgba(255,90,20,0.55), transparent 70%), linear-gradient(180deg, rgba(8,4,4,0.55) 0%, rgba(8,4,4,0.35) 40%, rgba(6,3,3,0.55) 100%), url('/images/badges/tex-inferno-gate.webp') center 30%/cover no-repeat, #0c0403",
    icon: '#ffb085',
    label: '#ffb085',
    inset: 2,
    gap: '#0c0403',
    filter: 'drop-shadow(0 0 10px rgba(255,90,20,0.45))',
  },
  stormLive: {
    outer:
      'linear-gradient(160deg, #f2f9ff 0%, #6fb6ff 16%, #1b2a44 38%, #cfeaff 54%, #24365a 74%, #8fd0ff 100%)',
    fill: "radial-gradient(90% 45% at 50% 8%, rgba(120,190,255,0.30), transparent 70%), linear-gradient(180deg, rgba(8,16,32,0) 0%, rgba(8,16,32,0.2) 34%, rgba(8,14,28,0.45) 60%, rgba(6,12,24,0.7) 100%), url('/images/badges/tex-storm-clouds.webp') center top/cover no-repeat, #0a1424",
    icon: '#dff1ff',
    label: '#cfeaff',
    inset: 2,
    gap: '#0a1424',
    filter: 'drop-shadow(0 0 9px rgba(111,182,255,0.45))',
  },
  olympus: {
    outer:
      'linear-gradient(150deg, #fff6d8 0%, #d4a845 16%, #8a6416 34%, #f7e3a0 50%, #a77a22 68%, #fff2c4 86%, #b8892a 100%)',
    fill: "linear-gradient(180deg, rgba(253,250,242,0) 0%, rgba(253,250,242,0.25) 42%, rgba(250,245,234,0.85) 62%, rgba(246,240,228,0.92) 100%), url('/images/badges/tex-olympus-temple.webp') center top/cover no-repeat, #f6f0e2",
    icon: '#2a1f0a',
    label: '#f2d27a',
    inset: 2.2,
    gap: '#f6f0e2',
    filter: 'drop-shadow(0 0 10px rgba(242,210,122,0.45))',
  },
}
