/**
 * GENERATED by docs/design/handoffs/2026-10-cards/import-badge-icons.mjs from the operator's
 * badge icons (spec D14). Families listed here draw /images/badges/icons/<id>.svg
 * as a tinted mask; the rest keep their lucide placeholder. Do not edit by hand.
 */
import type { BadgeFamilyId } from '@eanhl/db/cards'

export const BADGE_ICON_FILES: Readonly<Partial<Record<BadgeFamilyId, string>>> = {
  gg: '/images/badges/icons/gg.svg',
  gpoke: '/images/badges/icons/gpoke.svg',
  gsv: '/images/badges/icons/gsv.svg',
  gw: '/images/badges/icons/gw.svg',
  p3v3: '/images/badges/icons/p3v3.svg',
  p6g: '/images/badges/icons/p6g.svg',
  p6v6: '/images/badges/icons/p6v6.svg',
  pasts: '/images/badges/icons/pasts.svg',
  pblk: '/images/badges/icons/pblk.svg',
  pbrk: '/images/badges/icons/pbrk.svg',
  pfight: '/images/badges/icons/pfight.svg',
  pfo: '/images/badges/icons/pfo.svg',
  pgoals: '/images/badges/icons/pgoals.svg',
  phits: '/images/badges/icons/phits.svg',
  pht: '/images/badges/icons/pht.svg',
  pshots: '/images/badges/icons/pshots.svg',
  ptka: '/images/badges/icons/ptka.svg',
  pwins: '/images/badges/icons/pwins.svg',
}
