import {
  Apple,
  Award,
  BrickWall,
  CircleDot,
  Crosshair,
  Hammer,
  Hand,
  HeartPulse,
  Hexagon,
  Magnet,
  ScanFace,
  Shield,
  ShieldCheck,
  Siren,
  Sparkles,
  Sword,
  Swords,
  TrafficCone,
  Trophy,
  Unlink,
  Users,
  type LucideIcon,
} from 'lucide-react'
import type { BadgeFamilyId } from '@eanhl/db/cards'

/** Badge glyphs (badge-levels.js `glyph` names) as lucide-react components. */
export const BADGE_GLYPHS: Readonly<Record<BadgeFamilyId, LucideIcon>> = {
  p3v3: Users,
  p6v6: Hexagon,
  p6g: ShieldCheck,
  pwins: Trophy,
  pgoals: Siren,
  pasts: Apple,
  pshots: Crosshair,
  pdekes: TrafficCone,
  pht: Sparkles,
  pbrk: Unlink,
  phits: Hammer,
  pfo: CircleDot,
  ptka: Magnet,
  pblk: Shield,
  pfight: Swords,
  gg: ScanFace,
  gw: Award,
  gsv: Hand,
  gdsv: HeartPulse,
  gpoke: Sword,
  gso: BrickWall,
}
